// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSync(arg1) {
  return window['go']['main']['App']['CancelSync'](arg1);
}

export function ConfirmDeletes(arg1, arg2) {
  return window['go']['main']['App']['ConfirmDeletes'](arg1, arg2);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function PickFolder(arg1) {
  return window['go']['main']['App']['PickFolder'](arg1);
}

export function Progress(arg1) {
  return window['go']['main']['App']['Progress'](arg1);
}

export function ScanTask(arg1) {
  return window['go']['main']['App']['ScanTask'](arg1);
}

export function StartSync(arg1, arg2) {
  return window['go']['main']['App']['StartSync'](arg1, arg2);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}
