// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function CancelSync(arg1:string):Promise<void>;

export function ConfirmDeletes(arg1:string,arg2:boolean):Promise<void>;

export function CreateTask(arg1:main.TaskInput):Promise<models.SyncTask>;

export function DeleteTask(arg1:string):Promise<void>;

export function GetSettings():Promise<main.Settings>;

export function ListTasks():Promise<Array<models.SyncTask>>;

export function PickFolder(arg1:string):Promise<string>;

export function Progress(arg1:string):Promise<models.SyncProgress>;

export function ScanTask(arg1:string):Promise<models.FileDiff>;

export function StartSync(arg1:string,arg2:boolean):Promise<void>;

export function UpdateSettings(arg1:string):Promise<main.Settings>;

export function UpdateTask(arg1:string,arg2:main.TaskInput):Promise<models.SyncTask>;
